#! /bin/sh

### BEGIN INIT INFO
# Provides:          greeneyes-vsn
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: GreenEyes VSN
# Description:       Startup initialization script for GreenEyes VSN
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting GreenEyes VSN "
		cd /opt/greeneyes-vsn
		
		PID=`pidof greeneyes-vsn`
        if [ -n "$PID" ]
        then
            echo "GreenEyes VSN already running."
            exit 1
		fi

		if [ -f log.txt ]
		then tail -c 10M log.txt > log.prev.txt
		rm log.txt
		fi
		
		ifup wlan0 >>log.txt 2>&1
		sleep 5
		ifdown wlan0 >>log.txt 2>&1

		#Camera
		cpufreq-set -f 600M >>log.txt 2>&1
		#Cooperator
		#cpufreq-set -g ondemand --max 1000M >>log.txt 2>&1

		ifup wlan0 >>log.txt 2>&1
		iwlist wlan0 scan >>log.txt 2>&1

		#Camera 1
		ifconfig wlan0 192.168.200.55 netmask 255.255.255.0 >>log.txt 2>&1
		./greeneyes-vsn camera 11 --telos /dev/ttyUSB0 >>log.txt 2>&1 &
		#Camera 2
		#ifconfig wlan0 192.168.200.56 netmask 255.255.255.0 >>log.txt 2>&1		
		#./greeneyes-vsn camera 12 --telos /dev/ttyUSB0 >>log.txt 2>&1 &
		
		#Cooperator 1		
		#./greeneyes-vsn cooperator 21 >>log.txt 2>&1 &
		#Cooperator 2
		#./greeneyes-vsn cooperator 22 >>log.txt 2>&1 &
    ;;
  stop)
    echo "Stopping GreenEyes VSN"
    
    PID=`pidof greeneyes-vsn`

    if [ -z "$PID" ]
    then
        echo "GreenEyes VSN already stopped."
    else
	    pkill -quit greeneyes-vsn
	    while ps -p $PID  > /dev/null; do sleep 1; done;
    fi
    ;;
  restart)
    #echo "Restarting GreenEyes VSN"
	service greeneyes stop
	service greeneyes start

    ;;
  *)
    echo "Usage: sudo service greeneyes {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
